### ISSUE TITLE
关于两个运算符相连

### ISSUE THREAD

**Issue by AIflowerQ** [OO-guide-2019/homework-pre#2]
请问，本题中两个数字之间是否至多只能有两个运算符相连？

**Comment by HansBug** [comment]
请自己根据题目描述进行理解，根据题目描述的内容应该是可以得出答案的。。。
以及，我们并不鼓励此类型的提问

**Comment by HansBug** [comment]
具体的说下吧，
1、提问的最基本前提是已经对现有材料(教材，指导书，搜索引擎，技术文档等)进行过全面而仔细的研究
2、如果做了上一条后依然有疑问的话，请完整的说清楚疑问的前因后果(别告诉我没有)，贴上你疑问的逻辑，以及结合相应的资料内容，进行完整的阐述，并明确疑问的关键点在哪里
3、对于明显不合规的提问，在本课程中助教团队有权拒绝回复(回复一个带走理由解释的no response)并关闭提问。对于经常被no response的玩家，将会在最终成绩里面酌情扣分。(当然，对于经常有优质提问的玩家，也会考虑酌情加分)
4、此提问的问题在于，首先这个问题在出题的时候出题人就仔细考虑过，不应该存在问题。其次，就算真的确实存在问题，提问者也显然毫无前因后果的分析，给人一种伸手党的感觉。这是本课程(以及整个计算机行业)所不鼓励的行为

**Comment by PaParaZz1** [comment]
鉴于是第一个提问者，我们鼓励这样积极提问的行为，但是希望大家以后能认真思考上个comment的四点，做到优质提问。
关于这个问题本身，可以这样理解：
一个无符号整数前面**可以有**一个正号或负号，而一个表达式中有加号和减号，所以可能存在"1++2"，”+3-+5“这样的形式。而且，严格来讲这不叫两个运算符相连。
