### ISSUE TITLE
关于每行开头空格与结尾空格问题

### ISSUE THREAD

**Issue by Heyedanlty** [OO-guide-2019/homework-pre#3]
是否允许每行开头和结尾出现空格？
鉴于指导书没有指出是否允许开头结尾空格的问题，在此提出；
此问题主要针对第3个作业，看起来第三次作业的重点不是格式检查？

**Comment by PaParaZz1** [comment]
请参照指导书中内容认真理解，指导书中已经说明了必要的约束信息。
对于该问题，实质上是每一行从一个字符串中提取出有效的信息，可以思考一下具体的实现方式，相信能够理解指导书此处的设置。
