### ISSUE TITLE
有关“包含且仅包含两个合法的整数”的语义理解方式

### ISSUE THREAD

**Issue by shh2000** [OO-guide-2019/homework-pre#4]
请问，包含且仅包含两个合法的数，是说合法的数只能有两个，还是说这一行只有两个合法的数?（就类似世界只有一个中国，怎么理解?）如果前者的话，“2 *%? -3”这样的输入也是合理的?如果后者的话，空格怎么解释（空格并不属于合法的整数）

**Comment by HansBug** [comment]
首先，你并没讲清楚这个问题出自哪里，出自哪次作业。
其次，我问你，**包含且仅包含**是什么意思？
世界只有一个中国，是包含且仅包含一个中国的意思么？
**只有**这个词可能确实有歧义，但是你自己提问也都说了，原文是**包含且仅包含**。
这个提问中的解释本身就有偷换概念之嫌。

**Comment by HansBug** [comment]
顺带，我们一样不鼓励过度的咬文嚼字行为，更何况这里面夹带着偷换概念（第二句话还是**包含且仅包含**，从第三句起就成了**只有**）

**Comment by shh2000** [comment]
补：我想询问的是有关预习作业的第二题。谢谢助教，那按照包含且仅包含的定义，样例中的-+10000 300000包含了两个合法的整数（+10000和300000），两个整数用空格分隔开了，并且仅包含两个“合法的整数”（没有第三个了），请问这样的理解在哪里出现了问题

**Comment by HansBug** [comment]
很显然，这种逻辑看上去说得通，实际上说不通。
看得出来提问者是一个精通逻辑的同学，这值得赞许。
不过，精通逻辑的你也应该发现了另一个问题，如果按照这样解释的话，那么你的数据

`-+10000 300000`

也一样可以理解为`10000`和`3`，甚至是`0000`和`300`。
假设，你的理解成立，则这个问题本身就是无解的，或者说正解不唯一且不可判定。
假设，A成立可以推出B成立，但是B显然是不成立的，那么一定可以反推出A是不可能成立的。

所以，你的逻辑实际上并不能站得住脚。

**Comment by PaParaZz1** [comment]
不要过分咬文嚼字，死扣细节。。。出题人不会变着法的刁难你。
原始叙述的目的是，一行应该有且只有两个整数，空格只是分隔符的作用。没空格两个整数贴在一起你无法区分啊。。。我觉得没必要在指导书里还得专门单独说一句**空格是分隔符**。
然后你说的那个样例，属于整数格式错误，-+10000并不是定义中的整数。拆开成-和+10000，这就有点钻牛角尖了，希望以后不要过分纠结这样的无意义细节。

**Comment by shh2000** [comment]
好吧。。也就是说，这道题可以理解为侧重于找“**错误的格式**”而不是去**尽可能的**找到**两个合法的数**？谢谢助教们！
